image: node:8.12.0

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H '172.16.66.128' >> ~/.ssh/known_hosts

stages:
  - tests
  - deploy
  - production

version:
  stage: tests
  script:
  - node --version
  - whoami
  only:
  - dev
  - master

run_tests:
  stage: tests
  script:
  - npm install
  - npm test
  only:
  - dev
  - master

deploy_staging_dev:
  stage: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fjs-web.git
  - git push heroku dev:master
  - echo "Deployed to staging server"
  only:
  - dev

production_deploy:
  stage: production
  script:
  - git push dokku@172.16.66.128:fjsappadm master
  - echo "🔥 Deployed to PRODUCTION 🔥"
  only:
  - master
