image: node:8.12.0
stages:
  - tests
  - deploy

version:
  stage: tests
  script:
  - node --version
  - whoami
  only:
  - dev

run_tests:
  stage: tests
  script:
  - npm install
  - npm test
  only:
  - dev

deploy_staging_dev:
  stage: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fjs-web.git
  - git push heroku --delete dev
  - git push heroku dev:master
  - echo "Deployed to staging server"
  only:
  - dev
