staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=fjs-web --api-key=$HEROKU_API_KEY
  only:
  - dev

testing:
  type: test
    script:
    - npm test
    only:
    - dev
