image: node:6.10.3
staging:
  type: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fjs-web.git
  - git push heroku dev
  - echo "Deployed to staging server"
  only:
  - dev
