image: node:8.12.0
stages:
  - ver
  - init
  - tests
  - deploy

ver:
  stage: ver
  script:
  - node --version
  - whoami

init:
  stage: init
  script:
  - npm install
  only:
  - dev

run_tests:
  stage: tests
  script:
  - npm test
  only:
  - dev

deploy_staging:
  stage: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fjs-web.git
  - git push heroku dev
  - echo "Deployed to staging server"
  only:
  - dev
