image: node:8.12.0


stages:
  - deploy
  - production

deploy_staging_dev:
  stage: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fjs-web.git
  - git push heroku dev:master
  - echo "🧪 Deployed to staging server 🧪"
  only:
  - dev

production_deploy:
  stage: production
  before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'migserv.ucc.edu.ar' >> ~/.ssh/known_hosts

  script:
  - git push dokku@migserv.ucc.edu.ar:fjsappadm HEAD:master
  - echo "🔥 Deployed to PRODUCTION 🔥"
  only:
  - master
